version: '3.8'

#volumes:
#  data-p0:
#  data-p1:
#  data-p2:
#  data-p3:
  #player-data-p0:
  #player-data-p1:
  #player-data-p2:
  #player-data-p3:
  #persistence-p0:
  #persistence-p1:
  #persistence-p2:
  #persistence-p3:
  #mpc-bytecodes:
  #mpc-schedules:

services:

  mpcnode0:
    image: sbellem/hbswap:aws-0.0.21
    environment:
      NODE_ID: 0
      POA_KEYSTORE: /opt/poa/keystore
      POA_PWD_FILE: /run/secrets/poapwd
      INPUTMASK_SHARES: /opt/hbswap/data/inputmask-shares
    ports:
      - target: 8080
        published: 8080
        x-aws-protocol: https
        #volumes:
        #  - data-p0:/opt/hbswap/data
      #- persistence-p0:/usr/src/hbswap/Persistence
      #- player-data-p0:/usr/src/hbswap/Player-Data
      #- mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      #- mpc-schedules:/usr/src/hbswap/Programs/Schedules
    secrets:
      - P0.key
      - poapwd
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    #command: ["wait-for-it", "ethnode:8545", "--", "bash", "mpc-node.sh", "0", "ethnode", "mpcnode0"]
    command: ["bash", "mpc-node.sh"]

  mpcnode1:
    image: sbellem/hbswap:aws-0.0.21
    environment:
      NODE_ID: 1
      POA_KEYSTORE: /opt/poa/keystore
      POA_PWD_FILE: /run/secrets/poapwd
      INPUTMASK_SHARES: /opt/hbswap/data/inputmask-shares
    ports:
      - target: 8081
        published: 8081
        x-aws-protocol: https
        #volumes:
        #  - data-p1:/opt/hbswap/data
      #- persistence-p1:/usr/src/hbswap/Persistence
      #- player-data-p1:/usr/src/hbswap/Player-Data
      #- mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      #- mpc-schedules:/usr/src/hbswap/Programs/Schedules
    secrets:
      - P1.key
      - poapwd
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    #command: ["wait-for-it", "ethnode:8545", "--", "bash", "mpc-node.sh", "1", "ethnode", "mpcnode0"]
    command: ["bash", "mpc-node.sh"]

  mpcnode2:
    image: sbellem/hbswap:aws-0.0.21
    environment:
      NODE_ID: 2
      POA_KEYSTORE: /opt/poa/keystore
      POA_PWD_FILE: /run/secrets/poapwd
      INPUTMASK_SHARES: /opt/hbswap/data/inputmask-shares
    ports:
      - target: 8082
        published: 8082
        x-aws-protocol: https
        #volumes:
        #  - data-p2:/opt/hbswap/data
      #- persistence-p2:/usr/src/hbswap/Persistence
      #- player-data-p2:/usr/src/hbswap/Player-Data
      #- mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      #- mpc-schedules:/usr/src/hbswap/Programs/Schedules
    secrets:
      - P2.key
      - poapwd
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    #command: ["wait-for-it", "ethnode:8545", "--", "bash", "mpc-node.sh", "2", "ethnode", "mpcnode0"]
    command: ["bash", "mpc-node.sh"]

  mpcnode3:
    image: sbellem/hbswap:aws-0.0.21
    environment:
      NODE_ID: 3
      POA_KEYSTORE: /opt/poa/keystore
      POA_PWD_FILE: /run/secrets/poapwd
      INPUTMASK_SHARES: /opt/hbswap/data/inputmask-shares
    ports:
      - target: 8083
        published: 8083
        x-aws-protocol: https
        #volumes:
        #  - data-p3:/opt/hbswap/data
      #- persistence-p3:/usr/src/hbswap/Persistence
      #- player-data-p3:/usr/src/hbswap/Player-Data
      #- mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      #- mpc-schedules:/usr/src/hbswap/Programs/Schedules
    secrets:
      - P3.key
      - poapwd
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    #command: ["wait-for-it", "ethnode:8545", "--", "bash", "mpc-node.sh", "3", "ethnode", "mpcnode0"]
    command: ["bash", "mpc-node.sh"]

secrets:
  P0.key:
    file: secrets/P0.key
  P1.key:
    file: secrets/P1.key
  P2.key:
    file: secrets/P2.key
  P3.key:
    file: secrets/P3.key
  poapwd:
    file: secrets/poapwd.txt

   #P0-eth.key:
   #  file: poa/keystore/server_0/UTC--2021-04-19T15-37-15.803116068Z--37a25f181a43613e2917c650bd6d2f2bb26defd2
   #P1-eth.key:
   #  file: poa/keystore/server_1/UTC--2021-04-19T15-37-17.182679135Z--abbf7aedbb03f7fb09b6c7a41623ef67b97570b2
   #P2-eth.key:
   #  file: poa/keystore/server_2/UTC--2021-04-19T15-37-18.543896263Z--00377f482929288e237c50578553641a0a2e4ce2
   #P3-eth.key:
   #  file: poa/keystore/server_3/UTC--2021-04-19T15-37-19.908957459Z--ae76f3dfa7a7b1556bb49ee41663b7ac6be58da5


#x-aws-loadbalancer: "arn:aws:elasticloadbalancing:eu-west-3:809684608753:loadbalancer/app/myloadbalancer/1e6f0dad53bd4979"
#x-aws-loadbalancer: "arn:aws:elasticloadbalancing:eu-west-3:809684608753:loadbalancer/net/nlb-hbswap/091e4b24631f891e"
x-aws-cloudformation:
  Resources:
    #Mpcnode0TCP8080Listener:
    Mpcnode08080Listener:
      Properties:
        #LoadBalancerArn: "arn:aws:elasticloadbalancing:eu-west-3:809684608753:loadbalancer/app/myloadbalancer/1e6f0dad53bd4979"
        Certificates:
          # ratelang.org
          #- CertificateArn: "arn:aws:acm:eu-west-3:809684608753:certificate/389bba7c-26b9-45a7-9da9-fefeae053045"
          # honeybadgerswap.com
          #- CertificateArn: "arn:aws:acm:eu-west-3:809684608753:certificate/a9a750d5-b2f9-4c6c-a85e-23d9dae7e126"
          #- CertificateArn: "arn:aws:acm:eu-west-3:809684608753:certificate/62cba85a-242e-4215-afd9-7cee9f50b184"
          # www.honeybadgerswap.org
          - CertificateArn: "arn:aws:acm:eu-west-3:809684608753:certificate/411c840d-06c1-48c1-8a8c-8bb377f544fc"
          # (galois,legendre,abel).honeybadgerswap.org
          #- CertificateArn: "arn:aws:acm:ca-central-1:809684608753:certificate/ad92ab75-974c-4977-a530-9c73b023ec04"
          # (quark).honeybadgerswap.org
          #- CertificateArn: "arn:aws:acm:ca-central-1:809684608753:certificate/1c028ee9-4472-4bf8-8594-ae83c06f4af1"
        Protocol: HTTPS
      Type: AWS::ElasticLoadBalancingV2::Listener
    Mpcnode18081Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:eu-west-3:809684608753:certificate/411c840d-06c1-48c1-8a8c-8bb377f544fc"
        Protocol: HTTPS
      Type: AWS::ElasticLoadBalancingV2::Listener
    Mpcnode28082Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:eu-west-3:809684608753:certificate/411c840d-06c1-48c1-8a8c-8bb377f544fc"
        Protocol: HTTPS
      Type: AWS::ElasticLoadBalancingV2::Listener
    Mpcnode38083Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:eu-west-3:809684608753:certificate/411c840d-06c1-48c1-8a8c-8bb377f544fc"
        Protocol: HTTPS
      Type: AWS::ElasticLoadBalancingV2::Listener
